### ISSUE TITLE
GWLB support for Transit Gateway.

### ISSUE THREAD

**Issue by googrikko** [aws-samples/aws-gateway-load-balancer-code-samples#13]
GWLB should support Transit Gateway as a target.

**Comment by mohammad-wehbe** [comment]
hi, what if I want to add an Application loadbalancer behind spoke1 application, how can this be achived ? what are the chnages on routetable level?

**Comment by pmankad96** [comment]
Hello, I would suggest to read [VPC Routing Enhancements and GWLB Deployment Patterns](https://aws.amazon.com/blogs/networking-and-content-delivery/vpc-routing-enhancements-and-gwlb-deployment-patterns/) and [Design your firewall deployment for Internet ingress traffic flows](https://aws.amazon.com/blogs/networking-and-content-delivery/design-your-firewall-deployment-for-internet-ingress-traffic-flows/). I hope this helps.
