### ISSUE TITLE
Stack templates wont deploy due to deprecated Lambda Python runtime version being referenced

### ISSUE THREAD

**Issue by alistairpullen** [aws-samples/aws-gateway-load-balancer-code-samples#15]
### Problem

```CentralizedArchitectureApplianceVpc2Az.yaml``` stack template wont deploy due to deprecated Lambda Python runtime version being referenced.

```
2024-09-04 13:27:08 UTC+0100
	
VpceServiceName
	
CREATE_FAILED
	
-
	
Resource handler returned message: "The runtime parameter of python3.7 is no longer supported for creating or updating AWS Lambda functions. We recommend you use a supported runtime while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: obfuscated)" (RequestToken: obfuscated, HandlerErrorCode: InvalidRequest)
```

Testing with Runtime: python3.12 worked fine.

### Solution

1. Replace the deprecated Python runtime reference with the latest 3.x version.
Before:
```Runtime: python3.7```
After:
```Runtime: python3.12```
Code path - https://github.com/aws-samples/aws-gateway-load-balancer-code-samples/blob/main/aws-cloudformation/centralized_architecture/CentralizedArchitectureApplianceVpc2Az.yaml#L968

2. Update in Git repo.

3. Update the files in s3://tech-content-us-west-2.s3-us-west-2.amazonaws.com to make sure that the 1-click solution works as well.

**Comment by alistairpullen** [comment]
Due to this issue, the 1 click deployment is also broken.

https://us-west-2.console.aws.amazon.com/cloudformation/home?region=us-west-2#/stacks/create/template?stackName=GwlbCentralizedDemo&templateURL=https://tech-content-us-west-2.s3-us-west-2.amazonaws.com/aws-gwlb-cloudformation-samples/centralized-architecture/nested-stack/CentralizedArchitecturePrimary.yaml

Now I need to demo to customers, but host the files myself which is a bit of a pain.

**Comment by pmankad96** [comment]
Fixed. Thanks.
