### ISSUE TITLE
Spoke application 

### ISSUE THREAD

**Issue by geseib** [aws-samples/aws-gateway-load-balancer-code-samples#2]
Application instance in spoke VPC fail running userdata script. have to run manually after launch

**Comment by pmankad96** [comment]
Sorry to hear that. Can you provide the output for /var/log/cloud-init-output.log for an instance that failed running userdata script?

**Comment by f7o** [comment]
@pmankad96 My pull request addresses this issue: #1 
This happens because routing is not 100% in place before `user-data` is started.

Could you please have a look?

**Comment by pmankad96** [comment]
@f7o it might be possible. Adding a dependency seems like a good idea. I will go ahead and add it and observe.

**Comment by pmankad96** [comment]
PR merged. I will close this issue.
